version: '3'
services:
  aria2:
    build: ./aria2
    container_name: aria2-aria2
    volumes:
      - ./aria2:/aria2
      - ./downloads-tmp:/aria2-download
      - ./downloads:/aria2-complete
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 6800:6800
    networks:
      - docker-service
    restart: always

  aria-ng:
    build: ./ariaNg
    ports:
      - 81:80
    container_name: aria2-aria2Ng
    volumes:
      - ./ariaNg/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - aria2
    networks:
      - docker-service
    restart: always


networks:
    docker-service:
        external: true
